
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    env_file:
      - .env

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    depends_on:
      - db
    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env
    
    entrypoint: [ "python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
    mysql_data: